services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dummy123
    volumes:
      - ./.data/mongo:/data/db/

  redis:
    image: redis:7.0.0
    command: redis-server --requirepass dummy123
    ports:
      - '6379:6379'
    volumes:
      - ./.data/redis:/data/
